name: deploy
on:
  push:
    branches:
      - main
      - stage

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

  deploy:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale connection
        uses: tailscale/github-action@v2
        env:
          TAILSCALE_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci-cd

      - name: SSH into VPS and Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ "${{ github.base_ref }}" = "main" ]; then
              TARGET_DIR="taxi"
            elif [ "${{ github.base_ref }}" = "stage" ]; then
              TARGET_DIR="taxi-stage"
            else
              echo "Branch ${{ github.base_ref }} not supported"
              exit 1
            fi

            echo "Starting deployment: ~/apps/$TARGET_DIR/frontend"

            cd ~/apps/$TARGET_DIR/frontend

            git pull origin ${{ github.base_ref }}

            cd ..

            docker compose up --build -d frontend
