name: deploy
on: [pull_request]

permissions: {}

jobs:
  test-and-lint: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with: 
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies    
        run: npm ci

      - name: Run linter
        uses: super-linter/super-linter@v7.1.0

      - name: Run tests
        run: npm test

  deploy:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale connection
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci-cd

      - name: SSH into VPS and Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}        
          username: ${{ secrets.VPS_USER }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            if [ "${{ github.base_ref }}" = "main" ]; then
              TARGET_DIR="taxi"
            elif [ "${{ github.base_ref }}" = "stage" ]; then
              TARGET_DIR="taxi-stage"
            else
              echo "Branch ${{ github.base_ref }} not supported"
              exit 1
            fi

            echo "Starting deployment: ~/apps/$TARGET_DIR/frontend"

            cd ~/apps/$TARGET_DIR/frontend
            
            git pull origin ${{ github.base_ref }}
            
            cd ..
            
            docker compose up --build -d frontend